---
- hosts: all
  become: yes
  become_user: root

  vars:
    helloworld: Meow!
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install firewalld
      yum:
        name: firewalld

    - name: Stop firewalld
      service:
        name: firewalld
        state: stopped

    - name: Install the apache2 package
      yum:
        name: apache2

    - name: Start the apache2 service
      service:
        name: apache2
        state: started

    - name: Configure Cat App
      template:
        src: ../files/index.j2
        dest: /var/www/html/index.html
